version: 2

sources:
  - name: staging
    database: project-de-pnt
     # For postgres:
      #database: production
    schema: trip_data_pnt

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}